info:
  model: int-scaffold
packages:
- gitBranch: release/1.0.0
  gitServerName: aadiacc
  gitUrl: https://github.com/aadi-tripathi
  gitUsername: aadi-tripathi
  name: NewTest1Project
version: 1.0.0
